fix: check if adapters are running before starting larva scenario's

diff --git a/.github/workflows/run-larva-scenarios.yml b/.github/workflows/run-larva-scenarios.yml
--- a/.github/workflows/run-larva-scenarios.yml
+++ b/.github/workflows/run-larva-scenarios.yml
@@ -46,8 +46,31 @@ jobs:
               echo "Application did not become healthy within $timeout seconds. Failing the job."
               exit 1
             fi
-            echo "Waiting for application to be healthy..."
-            sleep 5
+          done
+
+          url="http://localhost:8080/iaf/api/adapters?expanded=all"
+
+          while true; do
+            # Fetch the response using curl
+            response=$(curl -s $url || echo "unreachable")
+            
+            # Check if the response contains 'stopped' or 'starting'
+            if echo "$response" | grep -qE "stopped|starting"; then
+              echo "Match found ('stopped' or 'starting' detected). Retrying in 2 seconds..."
+            elif [ "$response" = "unreachable" ]; then
+              echo "Host unreachable. Retrying in 2 seconds..."
+            else
+              echo "No matches found. Everything is running!"
+              break
+            fi
+
+            if [ $elapsed_time -ge $timeout ]; then
+              echo "Some adapters were not running after $timeout seconds. Failing the job."
+              exit 1
+            fi
+
+            # Wait for 2 seconds before retrying
+            sleep 2
           done
         timeout-minutes: 2
 
